/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Evaluation, Criterion, Employee } from '../types';

export interface ProductionInputParams {
  empCode: string;
  empName?: string;
  period: string;
  producedUnits: number;         // تعداد تولید واقعی (قطعه)
  targetUnits: number;           // برنامه تولید مصوب (قطعه)
  actualCycleTimeSec: number;    // سایکل‌تایم واقعی (ثانیه به ازای هر قطعه)
  standardCycleTimeSec: number;  // سایکل‌تایم استاندارد مهندسی (ثانیه)
  scrapUnits: number;            // تعداد قطعات معیوب و ضایعاتی
  workingHours: number;          // کل ساعات کاری موظفی شیفت (ساعت)
  downtimeHours: number;         // ساعات توقف خط یا خرابی دستگاه (ساعت)
  notes?: string;                // توضیحات تکمیلی اپراتور یا سرپرست
}

export interface ProductionCalculationResult {
  // راندمان تولید
  efficiencyRate: number;              // درصد راندمان تولید
  productionScore: number;             // نمره ۱ تا ۵ تحقق تولید

  // سایکل تایم
  cycleTimeVarianceSec: number;        // انحراف سایکل تایم نسبت به استاندارد (ثانیه)
  cycleTimeImprovementRate: number;    // درصد بهبود یا تاخیر سایکل تایم
  cycleTimeScore: number;              // نمره ۱ تا ۵ سایکل‌تایم

  // ضایعات و کیفیت
  scrapRate: number;                   // درصد ضایعات
  ppm: number;                         // Parts Per Million
  scrapScore: number;                  // نمره ۱ تا ۵ ضایعات
  qualityRate: number;                 // درصد قطعات سالم

  // اثربخشی کلی تجهیزات (OEE)
  availabilityRate: number;            // نرخ دسترس‌پذیری (Availability)
  performanceRate: number;             // نرخ عملکرد (Performance)
  oeeRate: number;                     // درصد OEE نهایی
  oeeScore: number;                    // نمره ۱ تا ۵ شاخص OEE

  // نمره ترکیبی شاخص‌های تولید
  overallKpiScore: number;             // میانگین نمره نهایی ۱ تا ۵

  // متن توجیهی و مستندسازی اتوماتیک
  autoGeneratedSummary: string;
  badgeLevel: 'عالی (A+)' | 'مطلوب (A)' | 'متوسط (B)' | 'نیازمند بهبود (C)' | 'بحرانی (D)';
}

/**
 * Calculates comprehensive industrial performance metrics from raw production parameters
 */
export function calculateProductionMetrics(params: ProductionInputParams): ProductionCalculationResult {
  const {
    producedUnits = 0,
    targetUnits = 0,
    actualCycleTimeSec = 0,
    standardCycleTimeSec = 0,
    scrapUnits = 0,
    workingHours = 0,
    downtimeHours = 0
  } = params;

  // 1. محاسبه راندمان تولید
  const safeTarget = targetUnits > 0 ? targetUnits : 1;
  const efficiencyRate = Number(((producedUnits / safeTarget) * 100).toFixed(2));
  
  let productionScore = 3;
  if (efficiencyRate >= 105) productionScore = 5;
  else if (efficiencyRate >= 100) productionScore = 4;
  else if (efficiencyRate >= 92) productionScore = 3;
  else if (efficiencyRate >= 80) productionScore = 2;
  else productionScore = 1;

  // 2. محاسبه سایکل‌تایم و انحراف نسبت به استاندارد مهندسی
  const cycleTimeVarianceSec = standardCycleTimeSec > 0 && actualCycleTimeSec > 0
    ? Number((standardCycleTimeSec - actualCycleTimeSec).toFixed(2))
    : 0;

  // اگر مقدار مثبت باشد یعنی سریع‌تر از استاندارد عمل کرده (بهبود)
  const cycleTimeImprovementRate = standardCycleTimeSec > 0 && actualCycleTimeSec > 0
    ? Number((((standardCycleTimeSec - actualCycleTimeSec) / standardCycleTimeSec) * 100).toFixed(2))
    : 0;

  let cycleTimeScore = 3;
  if (cycleTimeImprovementRate >= 5) cycleTimeScore = 5;      // بیش از ۵٪ سریع‌تر از استاندارد
  else if (cycleTimeImprovementRate >= 0) cycleTimeScore = 4;  // منطبق با استاندارد یا تا ۵٪ سریع‌تر
  else if (cycleTimeImprovementRate >= -7) cycleTimeScore = 3; // انحراف جزئی تا ۷٪ تاخیر
  else if (cycleTimeImprovementRate >= -15) cycleTimeScore = 2;// تاخیر تا ۱۵٪
  else cycleTimeScore = 1;                                     // تاخیر شدید بیش از ۱۵٪

  // 3. محاسبه ضایعات و قطعات معیوب
  const safeProduced = producedUnits > 0 ? producedUnits : 1;
  const safeScrap = Math.max(0, scrapUnits);
  const scrapRate = Number(((safeScrap / safeProduced) * 100).toFixed(2));
  const ppm = Math.round(scrapRate * 10000);
  const qualityRate = Number(Math.max(0, 100 - scrapRate).toFixed(2));

  let scrapScore = 3;
  if (scrapRate <= 0.8) scrapScore = 5;        // ضایعات عالی زیر ۰.۸٪
  else if (scrapRate <= 1.5) scrapScore = 4;   // ضایعات مطلوب تا ۱.۵٪
  else if (scrapRate <= 2.5) scrapScore = 3;   // ضایعات متوسط تا ۲.۵٪
  else if (scrapRate <= 4.0) scrapScore = 2;   // ضایعات بالا تا ۴٪
  else scrapScore = 1;                         // ضایعات بحرانی بیش از ۴٪

  // 4. محاسبه OEE (دسترس‌پذیری، کارایی، کیفیت)
  const safeWorkingHours = workingHours > 0 ? workingHours : 160;
  const safeDowntime = Math.min(safeWorkingHours, Math.max(0, downtimeHours));
  const availabilityRate = Number((((safeWorkingHours - safeDowntime) / safeWorkingHours) * 100).toFixed(2));

  // کارایی بر اساس سایکل‌تایم یا راندمان
  let performanceRate = 100;
  if (standardCycleTimeSec > 0 && actualCycleTimeSec > 0) {
    performanceRate = Number(Math.min(115, (standardCycleTimeSec / actualCycleTimeSec) * 100).toFixed(2));
  } else if (efficiencyRate > 0) {
    performanceRate = Number(Math.min(115, efficiencyRate).toFixed(2));
  }

  const oeeRate = Number(((availabilityRate * performanceRate * qualityRate) / 10000).toFixed(2));

  let oeeScore = 3;
  if (oeeRate >= 85) oeeScore = 5;       // سطح کلاس جهانی (World Class OEE)
  else if (oeeRate >= 75) oeeScore = 4;  // سطح بسیار خوب
  else if (oeeRate >= 65) oeeScore = 3;  // سطح پذیرفته کارخانه‌ای
  else if (oeeRate >= 50) oeeScore = 2;  // سطح نیازمند مداخله فنی
  else oeeScore = 1;                     // سطح غیرقابل قبول

  // 5. نمره ترکیبی کل (تولید، سایکل تایم، ضایعات، OEE)
  const overallKpiScore = Number(
    ((productionScore * 0.35) + (cycleTimeScore * 0.25) + (scrapScore * 0.25) + (oeeScore * 0.15)).toFixed(2)
  );

  let badgeLevel: ProductionCalculationResult['badgeLevel'] = 'متوسط (B)';
  if (overallKpiScore >= 4.5) badgeLevel = 'عالی (A+)';
  else if (overallKpiScore >= 3.8) badgeLevel = 'مطلوب (A)';
  else if (overallKpiScore >= 2.8) badgeLevel = 'متوسط (B)';
  else if (overallKpiScore >= 2.0) badgeLevel = 'نیازمند بهبود (C)';
  else badgeLevel = 'بحرانی (D)';

  // تولید متن اتوماتیک جهت درج در پرونده و مستندات
  const cycleDiffText = cycleTimeVarianceSec >= 0
    ? `${Math.abs(cycleTimeVarianceSec)} ثانیه سریع‌تر (+${cycleTimeImprovementRate}٪)`
    : `${Math.abs(cycleTimeVarianceSec)} ثانیه کندتر (${cycleTimeImprovementRate}٪)`;

  const autoGeneratedSummary = `داده‌های خودکار خط تولید: تولید ${producedUnits.toLocaleString('fa-IR')} قطعه (تحقق ${efficiencyRate}٪)، سایکل‌تایم ${actualCycleTimeSec}s در برابر استاندارد ${standardCycleTimeSec}s (${cycleDiffText})، ضایعات ${scrapRate}٪ (${ppm.toLocaleString('fa-IR')} PPM)، توقفات خط ${safeDowntime} ساعت، شاخص OEE: ${oeeRate}٪. نمره ارزیابی کمی: ${overallKpiScore} از ۵.`;

  return {
    efficiencyRate,
    productionScore,
    cycleTimeVarianceSec,
    cycleTimeImprovementRate,
    cycleTimeScore,
    scrapRate,
    ppm,
    scrapScore,
    qualityRate,
    availabilityRate,
    performanceRate,
    oeeRate,
    oeeScore,
    overallKpiScore,
    autoGeneratedSummary,
    badgeLevel
  };
}

/**
 * Injects calculated production metrics into an existing or new Evaluation record
 */
export function applyProductionMetricsToEvaluation(
  evaluation: Evaluation,
  criteria: Criterion[],
  calculation: ProductionCalculationResult,
  params: ProductionInputParams
): Evaluation {
  const updatedScores = evaluation.scores.map(scoreItem => {
    const crit = criteria.find(c => c.id === scoreItem.cid);
    if (!crit) return scoreItem;

    const critName = (crit.name || '').toLowerCase();
    const critCode = (crit.code || '').toUpperCase();
    const isKpi = crit.cat === 'K' || crit.cat === 'Q';

    // تطبیق با شاخص تحقق تولید
    if (critCode === 'K-01' || critName.includes('تولید') || critName.includes('خروجی نسبت به هدف')) {
      return {
        ...scoreItem,
        value: calculation.productionScore,
        doc: `تولید واقعی: ${params.producedUnits.toLocaleString('fa-IR')} از ${params.targetUnits.toLocaleString('fa-IR')} (راندمان: ${calculation.efficiencyRate}٪)`
      };
    }

    // تطبیق با شاخص سایکل تایم یا زمان تعویض قالب / سرعت خط
    if (critCode === 'K-11' || critName.includes('سایکل') || critName.includes('تعویض') || critName.includes('سرعت')) {
      return {
        ...scoreItem,
        value: calculation.cycleTimeScore,
        doc: `سایکل‌تایم واقعی: ${params.actualCycleTimeSec} ثانیه (استاندارد: ${params.standardCycleTimeSec} ثانیه | انحراف: ${calculation.cycleTimeImprovementRate}٪)`
      };
    }

    // تطبیق با شاخص ضایعات و کنترل کیفیت
    if (critCode === 'K-04' || critCode === 'Q-01' || critName.includes('ضایعات') || critName.includes('دوباره‌کاری')) {
      return {
        ...scoreItem,
        value: calculation.scrapScore,
        doc: `نرخ ضایعات: ${calculation.scrapRate}٪ (${params.scrapUnits.toLocaleString('fa-IR')} عدد معیوب | ${calculation.ppm.toLocaleString('fa-IR')} PPM)`
      };
    }

    // تطبیق با شاخص OEE و اثربخشی تجهیزات
    if (critCode === 'K-06' || critName.includes('oee') || critName.includes('اثربخشی کلی')) {
      return {
        ...scoreItem,
        value: calculation.oeeScore,
        doc: `شاخص اثربخشی کلی تجهیزات: ${calculation.oeeRate}٪ (دسترس‌پذیری: ${calculation.availabilityRate}٪ | کارایی: ${calculation.performanceRate}٪ | کیفیت: ${calculation.qualityRate}٪)`
      };
    }

    // تطبیق با توقفات خط
    if (critCode === 'K-07' || critName.includes('توقف')) {
      const downtimeScore = params.downtimeHours <= 2 ? 5 : params.downtimeHours <= 5 ? 4 : params.downtimeHours <= 10 ? 3 : params.downtimeHours <= 18 ? 2 : 1;
      return {
        ...scoreItem,
        value: downtimeScore,
        doc: `کل ساعات توقفات و خرابی دستگاه: ${params.downtimeHours} ساعت از ${params.workingHours} ساعت شیفت`
      };
    }

    return scoreItem;
  });

  return {
    ...evaluation,
    scores: updatedScores,
    note: evaluation.note 
      ? `${evaluation.note}\n\n[محاسبات تولید خودکار]: ${calculation.autoGeneratedSummary}`
      : `[محاسبات تولید خودکار]: ${calculation.autoGeneratedSummary}`
  };
}
